import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import test from "node:test";

const extensionDir = join(dirname(fileURLToPath(import.meta.url)), "../browser-extension");

test("browser extension uses narrow optional site permissions and localhost only", async () => {
  const manifest = JSON.parse(await readFile(join(extensionDir, "manifest.json"), "utf8"));
  assert.equal(manifest.manifest_version, 3);
  assert.equal(manifest.version, "0.8.0");
  assert.deepEqual(manifest.host_permissions, ["http://127.0.0.1:4765/*"]);
  assert.equal(manifest.optional_host_permissions.includes("<all_urls>"), false);
  assert.equal(manifest.optional_host_permissions.every((origin) => origin.startsWith("https://")), true);
  assert.equal(manifest.optional_host_permissions.includes("https://venice.ai/*"), true);
  assert.equal(manifest.optional_host_permissions.includes("https://github.com/*"), true);
  assert.equal(manifest.optional_host_permissions.includes("https://linear.app/*"), true);
  assert.equal(manifest.optional_host_permissions.includes("https://www.notion.so/*"), true);
  assert.equal(manifest.permissions.includes("webRequest"), false);
  assert.equal(manifest.permissions.includes("tabs"), false);
});

test("content capture observes submission events, not drafts or model traffic", async () => {
  const content = await readFile(join(extensionDir, "content.js"), "utf8");
  const background = await readFile(join(extensionDir, "background.js"), "utf8");
  const popup = await readFile(join(extensionDir, "popup.js"), "utf8");
  const popupMarkup = await readFile(join(extensionDir, "popup.html"), "utf8");
  assert.match(content, /addEventListener\("submit"/);
  assert.match(content, /addEventListener\("click"/);
  assert.match(content, /addEventListener\("keydown"/);
  assert.doesNotMatch(content, /addEventListener\(["']input["']/);
  assert.doesNotMatch(content, /localStorage|indexedDB|sessionStorage/);
  assert.doesNotMatch(background, /https:\/\//);
  assert.match(background, /PAIR_TOKEN_KEY/);
  assert.match(background, /\/v1\/browser\/open-home/);
  assert.doesNotMatch(background, /marketplace-device|AgentmonDevice/);
  assert.match(background, /AGENTMON_SITE_STATE/);
  assert.match(popup, /EXTENSION CONNECTED/);
  assert.match(popup, /Signal strength/);
  assert.match(popup, /permanent DNA event/);
  assert.match(content, /\/agentmon\\s\+/);
  assert.match(content, /AGENTMON DOWNLINK/);
  assert.match(background, /\/v1\/browser\/activate/);
  assert.match(background, /\/v1\/browser\/outcome/);
  assert.match(background, /\/v1\/browser\/route/);
  assert.match(content, /AGENTMON_ROUTE/);
  assert.match(popupMarkup, /\/agentmon auto main/);
  assert.match(popupMarkup, /AGENTMON MODE · THIS TAB/);
  assert.match(popup, /AGENTMON_AUTO_MODE/);
  assert.match(content, /AGENTMON_AUTO_MODE/);
  assert.match(content, /this tab/);
  assert.match(content, /proven procedure/);
  assert.match(content, /helped/);
  assert.match(content, /agentmon-local-receipt/);
  assert.match(content, /arena-proven skill/);
  assert.match(content, /Complete identity/);
  assert.match(content, /resonance/);
  assert.match(content, /Agentmon never reads the response/);
  assert.match(content, /AGENTMON_OUTCOME/);
  assert.match(popupMarkup, /STEP 1 OF 5/);
  assert.match(popup, /GET THE FIRST MEASURED WIN/);
  assert.match(popup, /IMPROVEMENT LOOP LIVE/);
  assert.match(popupMarkup, /ACTION LEARNING · THIS SITE/);
  assert.match(popupMarkup, /MARKETPLACE · AGENTMON HOME/);
  assert.match(popupMarkup, /Trading and registry credentials stay in the desktop app/);
  assert.match(popupMarkup, /TEMPORARY BATTLE STATE/);
  assert.match(popupMarkup, /Agentmon never guesses your feelings/);
  assert.match(popup, /AGENTMON_ACTION_EMOTION/);
  assert.match(background, /\/v1\/browser\/actions\/emotion/);
  assert.match(content, /semantic events only/);
  assert.match(content, /const PROMPT_SITES/);
  assert.match(content, /if \(!promptSite\) return/);
  assert.match(content, /Use Action Learning here/);
  assert.match(content, /input\[type="password"\]/);
  assert.doesNotMatch(content, /event:\s*\{[^}]*textContent/s);
  assert.doesNotMatch(background, /chrome\.storage\.local\.set\([^)]*content/s);
});
